import re
import subprocess
from datetime import datetime, timedelta, timezone

import capture


PDT = timezone(timedelta(hours=-7))


def test_compact_timestamp_negative_offset():
    moment = datetime(2026, 5, 23, 15, 57, 43, tzinfo=PDT)
    assert capture.compact_timestamp(moment) == "20260523T155743-0700"


def test_compact_timestamp_positive_half_hour_offset():
    moment = datetime(2026, 5, 23, 15, 57, 43, tzinfo=timezone(timedelta(hours=5, minutes=30)))
    assert capture.compact_timestamp(moment) == "20260523T155743+0530"


def test_compact_timestamp_naive_gets_local_offset():
    stamp = capture.compact_timestamp(datetime(2026, 5, 23, 15, 57, 43))
    assert re.fullmatch(r"\d{8}T\d{6}[+-]\d{4}", stamp)


def test_make_run_id_with_commit():
    moment = datetime(2026, 5, 23, 15, 57, 43, tzinfo=PDT)
    assert capture.make_run_id("75027e8", moment) == "20260523T155743-0700_75027e8"


def test_make_run_id_without_git_is_colon_free():
    run_id = capture.make_run_id(None, datetime(2026, 5, 23, 15, 57, 43, tzinfo=PDT))
    assert run_id.endswith("_nogit")
    assert ":" not in run_id


def _git(cwd, *args):
    subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True)


def test_git_commit_info_in_a_repo(tmp_path, monkeypatch):
    monkeypatch.setenv("GIT_CEILING_DIRECTORIES", str(tmp_path.parent))
    _git(tmp_path, "init", "-q")
    _git(tmp_path, "config", "user.email", "test@example.com")
    _git(tmp_path, "config", "user.name", "Test")
    (tmp_path / "f.txt").write_text("x", encoding="utf-8")
    _git(tmp_path, "add", "f.txt")
    _git(tmp_path, "commit", "-q", "-m", "init")
    expected = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"], cwd=tmp_path, capture_output=True, text=True, check=True
    ).stdout.strip()

    commit, committed_at = capture.git_commit_info(cwd=tmp_path)

    assert commit == expected
    assert committed_at.tzinfo is not None


def test_git_commit_info_outside_a_repo(tmp_path, monkeypatch):
    monkeypatch.setenv("GIT_CEILING_DIRECTORIES", str(tmp_path.parent))
    assert capture.git_commit_info(cwd=tmp_path) == (None, None)


from types import SimpleNamespace

import torch


class FakeTokenizer:
    """Byte-level: ids 0-255 are bytes, 256 is BOS, 257 is EOS."""

    BOS, EOS = 256, 257

    def get_bos_token_id(self):
        return self.BOS

    def get_eos_token_id(self):
        return self.EOS

    def get_vocab_size(self):
        return 258

    def encode(self, text):
        return list(text.encode("utf-8"))

    def decode(self, ids):
        return bytes(i for i in ids if i < 256).decode("utf-8", errors="replace")


class FakeModel(torch.nn.Module):
    """Next-token logits depend only on the last token, from a fixed random table."""

    def __init__(self, seq_len=64, eos_bias=0.0, fail=False):
        super().__init__()
        weights = torch.randn(258, 258, generator=torch.Generator().manual_seed(0))
        self.table = torch.nn.Embedding.from_pretrained(weights)
        self.config = SimpleNamespace(sequence_len=seq_len)
        self.eos_bias = eos_bias
        self.fail = fail
        self.calls = 0
        self.max_len_seen = 0

    def forward(self, idx):
        self.calls += 1
        self.max_len_seen = max(self.max_len_seen, idx.size(1))
        if self.fail:
            raise RuntimeError("boom")
        logits = self.table(idx).clone()
        logits[..., FakeTokenizer.EOS] += self.eos_bias
        return logits


def _sample(model, prompt="Once upon a time", **overrides):
    kwargs = dict(seed=1234, temperature=0.8, top_k=40, min_chars=40, max_tokens=60, device="cpu")
    kwargs.update(overrides)
    return capture.sample_continuation(model, FakeTokenizer(), prompt, **kwargs)


def test_same_seed_same_text():
    model = FakeModel()
    assert _sample(model) == _sample(model)


def test_different_seed_different_text():
    model = FakeModel()
    assert _sample(model, seed=1) != _sample(model, seed=2)


def test_global_rng_untouched():
    torch.manual_seed(7)
    before = torch.get_rng_state()
    _sample(FakeModel())
    assert torch.equal(before, torch.get_rng_state())


def test_training_mode_restored():
    model = FakeModel()
    model.train()
    _sample(model)
    assert model.training is True


def test_stops_at_eos():
    assert _sample(FakeModel(eos_bias=1e4)) == ""


def test_stops_once_min_chars_reached():
    text = _sample(FakeModel(), min_chars=10, max_tokens=300)
    assert 10 <= len(text) <= 12


def test_respects_max_tokens():
    text = _sample(FakeModel(), min_chars=10_000, max_tokens=5)
    assert len(text) <= 5  # each generated byte decodes to at most one character


def test_crops_context_to_sequence_len():
    model = FakeModel(seq_len=8)
    _sample(model, prompt="a prompt much longer than eight tokens")
    assert model.max_len_seen <= 8
